options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1            # Taiwan
  _REPO: cloud-run-source-deploy # 你在 AR 的 docker repo 名稱
  _SERVICE: cicdgame-cr          # 你的 Cloud Run 服務名稱（手動 deploy 用）
  _PLATFORM: managed

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}'
      - '.'

  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}'
