options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _REPO: cloud-run-source-deploy
  _SERVICE: cicdgame-cr
  _PLATFORM: managed
  _TAG: latest

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"
        echo "Deploying image: ${IMAGE}"
        gcloud run deploy ${_SERVICE} \
          --image="${IMAGE}" \
          --region="${_REGION}" \
          --platform="${_PLATFORM}" \
          --allow-unauthenticated
