options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _REPO: cicdgame
  _SERVICE: cicdgame
  _PLATFORM: managed
  _TAG: latest   # 執行 Trigger 時用表單改成 SID 或 SHORT_SHA

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}"
        echo "Deploying $IMAGE to Cloud Run service ${_SERVICE} in ${_REGION}"
        gcloud run deploy ${_SERVICE} \
          --image="$IMAGE" \
          --region="${_REGION}" \
          --platform="${_PLATFORM}" \
          --allow-unauthenticated
