options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1            # 你的區域
  _REPO: cicdgame                # Artifact Registry repo 名
  _SERVICE: cicdgame             # 服務/映像名
  _PLATFORM: managed

steps:
  # Step 1: build 從 backend/ 的 Dockerfile
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f", "backend/Dockerfile",                                             # 指定 Dockerfile 在 backend/
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}",
        "backend"                                                               # build context 指向 backend/ 資料夾
      ]

  # Step 2: push 到 Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      ]

  # Step 3（可選）: 從分支名抓學號，幫同一張 image 加 :<SID> 別名 tag
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        SID=$(echo "$BRANCH_NAME" | sed -E 's/^submission-([0-9]+)-.*$/\1/')
        if [[ "$SID" =~ ^[0-9]{8,10}$ ]]; then
          gcloud artifacts docker tags add \
            ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA} \
            ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SID} \
            --location=${_REGION}
        else
          echo "Branch $BRANCH_NAME has no valid SID; skip alias."
        fi

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"
