options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _REPO: cicdgame
  _SERVICE: cicdgame
  _PLATFORM: managed

steps:
  # Step 1: build image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}",
        "."
      ]

  # Step 2: push image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      ]

  # Step 3 (可選): 從 branch 名抓 SID，加上 tag
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        SID=$(echo "$BRANCH_NAME" | sed -E 's/^submission-([0-9]+)-.*$/\1/')
        if [[ "$SID" =~ ^[0-9]{8,10}$ ]]; then
          gcloud artifacts docker tags add \
            ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA} \
            ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SID} \
            --location=${_REGION}
        else
          echo "Branch $BRANCH_NAME 沒有符合的學號，略過 tagging"
        fi
